import CoreGraphics
import Foundation
import ImageIO
import XCTest
@testable import ProfileCuratorCore

/// Exercises the real Apple Vision and OCR -> navigation-candidate consumer path
/// using a programmatically generated, wholly fictitious screen.
final class VisualAgentNativeImageTests: XCTestCase {
    func testSyntheticScreenshotGeneratesGroundedNavigationCandidates() throws {
        guard let path = ProcessInfo.processInfo.environment["VISUAL_AGENT_SYNTHETIC_PNG"] else {
            throw XCTSkip("Optional native synthetic screenshot was not generated")
        }
        let url = URL(fileURLWithPath: path)
        guard let imageSource = CGImageSourceCreateWithURL(url as CFURL, nil),
              let image = CGImageSourceCreateImageAtIndex(imageSource, 0, nil) else {
            return XCTFail("Expected a loadable synthetic PNG generated by the local script")
        }
        XCTAssertEqual(image.width, 420)
        XCTAssertEqual(image.height, 932)

        let analysis = try VisionFixtureAnalyzer().analyze(image)
        let observation = ObservationSnapshotBuilder().build(from: analysis, image: image)
        XCTAssertEqual(observation.screen.kind, .profilePersonalInfo,
                       "Synthetic Personal Info anchor must be recognized")

        let frame = try VisualAgentFrameAdapter().build(
            screenshotDigest: "synthetic-fixture-only-image-digest",
            observation: observation,
            analysis: analysis
        )
        XCTAssertEqual(frame.stableObservationID, observation.fingerprint)
        let labels = Set(frame.elements.map(\.label))
        XCTAssertTrue(labels.contains("About Me"), "Expected a grounded About Me tab")
        XCTAssertTrue(labels.contains("Moments"), "Expected a grounded Moments tab")
        XCTAssertFalse(frame.elements.contains(where: { VisualAgentSafetyGate.isForbiddenControl($0.label) }))
        XCTAssertTrue(frame.elements.allSatisfy { $0.bounds.isValidNormalizedRect })
    }
}
