import Foundation
import ProfileCuratorCore

enum SimulationCLIError: Error { case invalidArguments, invalidFixtures, failedProof }

/// Reuses the compiled native core. All images must be generated by the accompanying
/// shell runner. The decision JSON is explicitly synthetic and no model is called.
@main
enum VisualAgentSimulationCLI {
    static func main() async throws {
        guard CommandLine.arguments.count == 3 else { throw SimulationCLIError.invalidArguments }
        let directory = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
        let decisionsURL = URL(fileURLWithPath: CommandLine.arguments[2])
        let decisionBytes = try Data(contentsOf: decisionsURL)
        let objects = try JSONSerialization.jsonObject(with: decisionBytes) as? [[String: Any]] ?? []
        let responses = try objects.map {
            String(decoding: try JSONSerialization.data(withJSONObject: $0, options: [.sortedKeys]), as: UTF8.self)
        }
        guard responses.count == 3 else { throw SimulationCLIError.invalidFixtures }
        let profile = try VisualAgentLocalImageFrame.load(at: directory.appendingPathComponent("profile.png"))
        let moments = try VisualAgentLocalImageFrame.load(at: directory.appendingPathComponent("moments.png"))
        let scrolled = try VisualAgentLocalImageFrame.load(at: directory.appendingPathComponent("moments-scrolled.png"))
        let ad = try VisualAgentLocalImageFrame.load(at: directory.appendingPathComponent("ad.png"))
        let unknown = try VisualAgentLocalImageFrame.load(at: directory.appendingPathComponent("unknown.png"))
        guard profile.screenKind == "profilePersonalInfo", moments.screenKind == "momentsFeed",
              scrolled.screenKind == "momentsFeed", moments.stableObservationID != scrolled.stableObservationID,
              ad.screenKind == "interstitialAd", unknown.screenKind == "unknown",
              ad.elements.isEmpty, unknown.elements.isEmpty else { throw SimulationCLIError.invalidFixtures }
        let normal = await VisualAgentSimulationLoop().run(planner: VisualAgentScriptedPlanner(responses: responses),
            host: VisualAgentSimulatedHost(initialFrame: profile, effects: [.observe(moments), .observe(scrolled)]))
        guard normal.verifiedActions == 2, normal.acknowledgedDispatches == 2,
              normal.stopReason == .plannerPause else { throw SimulationCLIError.failedProof }

        let recovery = await VisualAgentSimulationLoop().run(planner: ObstructionRecoveryPlanner(first: responses[0]),
            host: VisualAgentSimulatedHost(initialFrame: profile, effects: [.observe(ad)]))
        guard recovery.verifiedActions == 0, recovery.acknowledgedDispatches == 1,
              recovery.stopReason == .plannerPause,
              recovery.events.contains(where: { $0.stage == "recovery" }) else { throw SimulationCLIError.failedProof }

        let noReceipt = await VisualAgentSimulationLoop().run(planner: VisualAgentScriptedPlanner(responses: responses),
            host: VisualAgentSimulatedHost(initialFrame: profile, effects: [.withholdReceipt]))
        guard noReceipt.stopReason == .missingReceipt, noReceipt.acknowledgedDispatches == 0,
              noReceipt.verifiedActions == 0 else { throw SimulationCLIError.failedProof }

        let stale = VisualAgentProposal(frameID: profile.id, action: .tapElement, elementID: "tab-moments",
            expectation: .init(kind: .screenKind, value: "momentsFeed"), confidence: 0.95, rationale: "Synthetic duplicate response")
        let staleJSON = String(decoding: try JSONEncoder().encode(stale), as: UTF8.self)
        let duplicate = await VisualAgentSimulationLoop().run(planner: VisualAgentScriptedPlanner(responses: [staleJSON, staleJSON]),
            host: VisualAgentSimulatedHost(initialFrame: profile, effects: [.observe(moments)]))
        guard duplicate.verifiedActions == 1, duplicate.acknowledgedDispatches == 1,
              duplicate.stopReason == .rejectedProposal,
              duplicate.events.contains(where: { $0.detail == "rejected: staleFrame" }) else { throw SimulationCLIError.failedProof }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let reports = ["normal": normal, "obstructionRecovery": recovery, "missingReceipt": noReceipt, "staleDuplicate": duplicate]
        print(String(decoding: try encoder.encode(reports), as: UTF8.self))
    }
}

/// Chooses STOP from the observed obstruction + failed semantic result. The host
/// does not select this response or derive its next frame from model assertions.
struct ObstructionRecoveryPlanner: VisualAgentSimulationPlanner {
    let first: String
    func response(to request: VisualAgentSimulationRequest) async throws -> Data? {
        if request.step == 0 {
            return try await VisualAgentScriptedPlanner(responses: [first]).response(to: request)
        }
        guard request.previousVerification == .replan, request.frame.screenKind == "interstitialAd" else {
            throw SimulationCLIError.failedProof
        }
        return try JSONEncoder().encode(VisualAgentProposal(frameID: request.frame.id, action: .pause,
            confidence: 1, rationale: "Synthetic decision fixture: observed ad after failed navigation; STOP"))
    }
}
